# Generated by Django 5.1 on 2024-10-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fooditem_category_fooditem_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='user',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='location',
            field=models.CharField(help_text='Enter the place name or address.', max_length=255),
        ),
    ]
